// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLJSuM3mIPe_35UuqlmbRpgPDoW0xLUvs',
    appId: '1:102143585564:web:9e0d2baeec4166c6251ed9',
    messagingSenderId: '102143585564',
    projectId: 'kloudshop-dev',
    authDomain: 'kloudshop-dev.firebaseapp.com',
    storageBucket: 'kloudshop-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRwZAcvksia8P51iigXKD_5SDZ_NFf_U',
    appId: '1:102143585564:android:d4c689feeb12a4ba251ed9',
    messagingSenderId: '102143585564',
    projectId: 'kloudshop-dev',
    storageBucket: 'kloudshop-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF8YdaqDNKWFfEtTMRyBl5bKmRthp1wFA',
    appId: '1:102143585564:ios:9b6c20a476638fdd251ed9',
    messagingSenderId: '102143585564',
    projectId: 'kloudshop-dev',
    storageBucket: 'kloudshop-dev.firebasestorage.app',
    iosBundleId: 'biz.kloudshop.kloudshop',
  );
}
