import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:kloudshop/services/version_check_service.dart';
import 'package:kloudshop/app.dart';
// Generated by `flutterfire configure` — run this if the app fails to init Firebase.
// ignore: uri_does_not_exist
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with generated options.
  // If firebase_options.dart has not been generated yet, the app gracefully
  // falls through to the landing page — run `flutterfire configure` to fix.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('[Firebase] Initialized successfully.');
  } catch (e) {
    debugPrint('[Firebase] Init skipped — run `flutterfire configure`: $e');
  }

  // ASM-06: Check for new version and force reload if necessary.
  await VersionCheckService.checkVersion();

  runApp(
    const ProviderScope(
      child: KloudShopApp(),
    ),
  );
}

